name: StckUtils
api-version: 1.17
authors:
  - StckOverflw
main: de.stckoverflw.stckutils.StckUtilsPlugin
version: 0.0.1
libraries:
  - "net.axay:kspigot:1.17.2"

commands:
  timer:
    description: Start stop and reset the Timer
  settings:
    description: Opens the Settings GUI