name: StckUtils
api-version: 1.17
authors:
  - StckOverflw
  - l4zs
main: de.stckoverflw.stckutils.StckUtilsPlugin
version: 1.0.0
libraries:
  - "net.axay:kspigot:1.17.2"

commands:
  timer:
    description: Start stop and reset the Timer
  settings:
    description: Opens the Settings GUI